Experimental validation of the algorithm
skinnersp/exPfact pull request #2
Opened 2021-12-06 16:29 UTC by m-stofella

**Main modifications**
- The folder `validation` contains data and inputs to reproduce the results shown in the README file (and in the paper), which validate the method via a comparison with more accurate NMR measurements.
- Scripts are now written in python (no bash or fortran), with the exception of the clustering algorithm which requires R.
- All scripts have been passed through flake8 linter
- Some unit tests have been added in the folder `python` (the pytest library is used)
- All the readme files have been updated to be as much user-friendly as possible.
- All the scripts now work in a Windows operating system.

2021-12-10 20:05 UTC, skinnersp requested changes

2021-12-10 20:05 UTC, skinnersp commented on README.md
> +ExPfact is a statistically robust approach to estimate protection factors at resolution of the single amide from sparse and underdetermined HDX-MS data. Depending on the quality of the dataset analys
I think this should read: "ExPfact returns one of more possible patterns of...". Discrete is implied by the fact that the patterns are countable

2021-12-10 20:05 UTC, skinnersp commented on python/Hisotope.py
> +"""
It would be a good idea to stick the licence blurb for the GPL on the top of all code files and add (C) Emanuele Paci, Simon P Skinner, Michele Stofella in the appropriate place

2021-12-10 20:05 UTC, skinnersp commented on python/Hisotope.py
> +    isenv = {}
I presume this is the isotopic envelope? Would be good to use the full name here and snake case it, Explicit is better than implicit (The Zen of Python)

2021-12-10 20:05 UTC, skinnersp commented on python/Hisotope.py
> +        print("Fully protonated envelope saved in file "+sequence+".txt!")
Do we want to use a logger and write to a log file rather than print to the terminal with these messages?

2021-12-10 20:05 UTC, skinnersp commented on python/calc_dpred_python.py
>      frag_rates = res2frag(kint_list, time_points)
I think some of these variable names could also do with being more explicit, granted I wrote them. If you could change these to more informative names, that would make the code more readable.

2021-12-10 20:05 UTC, skinnersp commented on python/calculate.py
> +            scores.append(k*(params[ii-1]-2*params[ii]+params[ii+1])**2)
I think you're missing spaces around the arithmetic operators here

2021-12-10 20:05 UTC, skinnersp commented on python/calculate.py
> +        rms = [weights[i]*(dpred[i]-dexp[i])**2 for i in range(len(dexp))]
We should probably add spaces between the * here and those below

2021-12-10 20:05 UTC, skinnersp commented on python/calculate.py
> +                      and ii+1 not in prolines and ii+1 in pfactor_filter
spaces around +s

2021-12-10 20:05 UTC, skinnersp commented on python/clustering.py
> +    residues = [i+1 for i in range(max(ass.T[2]))]
spaces around +s and -s

2021-12-10 20:05 UTC, skinnersp commented on python/clustering.py
> +                area = str(first+1)+'-'+str(second+1)
I think string formatting here would be more pythonic

2021-12-10 20:05 UTC, skinnersp commented on python/clustering.py
> +    parser = argparse.ArgumentParser()
Is this idea to run each of these scripts sequentially, rather than have a main function that calls everything in turn?

2021-12-10 20:05 UTC, skinnersp commented on python/constants_DH.py
> +def get_l_DTR(temperature):
maybe expand the acronym of DTR? I don't know what that means.

2021-12-10 20:05 UTC, skinnersp commented on python/constants_DH.py
> +    return (1./temperature-1/293.)/R
as R is a float, you don't need to have the decimals for 1. and 293 - also spacing around operators

2021-12-10 20:05 UTC, skinnersp commented on python/cross_validation.py
> +    and M peptides     into a training dataset composed by all N time points
too many spaces between peptides and into

2021-12-10 20:05 UTC, skinnersp commented on python/cross_validation.py
> +    except the k-th index (1<=k<=N)     and a test dataset composed
too many spaces between (1<=k<=N) and and

2021-12-10 20:05 UTC, skinnersp commented on python/cross_validation.py
> +    CVtrain = 0
cv_train, cv_test - variables in Python rarely start with capitals, only classes do

2021-12-10 20:05 UTC, skinnersp commented on python/cross_validation.py
> +        out_file = "CVout.rm"+str(k)
string formatting instead?

2021-12-10 20:05 UTC, skinnersp commented on python/cross_validation.py
> +def L1OUT_dataset(dexp, time_points, k):
Leave one out is generally abbreviated to loo rather than L1OUT, initially I thought this had something to do with the L1 norm,

2021-12-10 20:05 UTC, skinnersp commented on python/descriptive.py
> +"""
I'd rename this to descriptive_statistics as without context the adjective on its own is a bit meaningless

2021-12-10 20:05 UTC, skinnersp commented on python/descriptive.py
> +def select_top_solutions(out_file, X):
top how many solutions? Should this be select_top_n_solutions and X becomes n? I generally expect X to be a set of features rather than a value of N

2021-12-10 20:05 UTC, skinnersp commented on python/exPfact.py
> +                          or ii+1 in pfactor_filter
ii + 1

2021-12-10 20:05 UTC, skinnersp commented on python/exPfact.py
> +            Nrep = int(opts.rep)
n_rep

2021-12-10 20:05 UTC, skinnersp commented on python/isenv.py
> +"""
rename to isotopic_envelope

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def sort_nicely(lst):
natural_sort maybe?

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +    P = np.exp(lnP)
p rather than P

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def single_deut_up(t, kint, lnP):
single_deuterium_uptake?

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +        return 1-np.exp(-kint/P*t*60)
spaces around operators

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def single_deut_do(t, kback, lnP):
can this function name be more descriptive? I don't know what it means

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def set_A_group(a, k):
why a capital A?

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def prob(k, t, kint, lnP):
probability or proba - the latter is used in sklearn

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def prob_do(k, t, kint, lnP):
what does the do here signify?

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +            f[i] += fr0[i+j]*fr[j]
spaces around operators

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +    ''' Calculate fully protonated isotopic envelope '''
You don't need triple quotes for an inline comment, # is much more common

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +    ''' Calculate isotopic envelopes at different times '''
see above

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +        with open(out_file+'.'+str(i)+'.isot', 'w+') as f:
string formatting

2021-12-10 20:05 UTC, skinnersp commented on python/isenv_functions.py
> +def sticks_from_exp_envelope(exp_env, corr_env, z):
experimental_envelope?

2021-12-10 20:05 UTC, skinnersp commented on python/kback.py
> +                prolines.append(first_residue + jj)
spaces around operators

2021-12-10 20:05 UTC, skinnersp commented on python/kint.py
> +        rho2 += +cst.rho_Nterm_base
double +?

2021-12-10 20:05 UTC, skinnersp commented on python/kint.py
> +        lamb = log10(10**(-0.90-pH)/(10**(-cst.get_pK_asp(temperature))+10**(-pH))+10**(0.90-cst.get_pK_asp(temperature))/(10**(-cst.get_pK_asp(temperature))+10**(-pH)))
spaces around operators

2021-12-10 20:05 UTC, skinnersp commented on python/tests.py
> +"""
I'd put your tests in separate files for each set of functions they test, it makes maintaining the code easier and keeps files as short as possible

2021-12-14 15:14 UTC, m-stofella commented on README.md
> +ExPfact is a statistically robust approach to estimate protection factors at resolution of the single amide from sparse and underdetermined HDX-MS data. Depending on the quality of the dataset analys
ExPfact does not return "one of more possible patterns", but classifies all possible patterns into a (finite) number of clusters. In some regions, there are multiple patterns returned by ExPfact. This is why I think "ExPfact returns one or a discrete number of possible patterns..." is more correct. I will replace discrete with finite.

2021-12-14 15:15 UTC, m-stofella commented on python/Hisotope.py
> +        print("Fully protonated envelope saved in file "+sequence+".txt!")
I thought about this and could do it, but does it make sense to create a log file just to say where the file has been saved?

2021-12-14 15:47 UTC, m-stofella commented on python/calc_dpred_python.py
>      frag_rates = res2frag(kint_list, time_points)
I noticed this script is useless since it's never used. Anyway, I changed these variables in the .pyx file that is then cythonized.

2021-12-14 15:47 UTC, m-stofella commented on python/calc_dpred_python.py
>      frag_rates = res2frag(kint_list, time_points)
(and I deleted this file instead)

2021-12-16 14:34 UTC, m-stofella commented on python/clustering.py
> +    parser = argparse.ArgumentParser()
Not sure what do you mean with this?

2021-12-16 14:35 UTC, m-stofella commented
I have addressed and resolved most change requests. I left some notes on a couple of unsolved comments.

2021-12-18 09:45 UTC, skinnersp commented on python/Hisotope.py
> +        print("Fully protonated envelope saved in file "+sequence+".txt!")
This is true for where a file is saved, but there is more than one place where a message is printed out to the screen for the benefit of the user and rather than putting all of this out into the terminal, a log file makes things searchable - equally the user could just redirect stdout to a file on the command line. If you're happy with the latter, we can resolve this point, and I'll approve and merge the PR

2021-12-20 12:33 UTC, m-stofella commented on python/Hisotope.py
> +        print("Fully protonated envelope saved in file "+sequence+".txt!")
A "logs" folder is now generated in the working directory and a new log file is created.

2021-12-27 07:34 UTC, skinnersp approved these changes

2021-12-27 07:34 UTC, merged